/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@inspirationlabs/router';

export namespace Components {
  interface IlSiteLoader {
    /**
    * The base domain for the project
    */
    'baseDomain': string;
    /**
    * Check for a router match
    */
    'match': MatchResults;
  }
}

declare global {


  interface HTMLIlSiteLoaderElement extends Components.IlSiteLoader, HTMLStencilElement {}
  var HTMLIlSiteLoaderElement: {
    prototype: HTMLIlSiteLoaderElement;
    new (): HTMLIlSiteLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'il-site-loader': HTMLIlSiteLoaderElement;
  }
}

declare namespace LocalJSX {
  interface IlSiteLoader {
    /**
    * The base domain for the project
    */
    'baseDomain'?: string;
    /**
    * Check for a router match
    */
    'match'?: MatchResults;
  }

  interface IntrinsicElements {
    'il-site-loader': IlSiteLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'il-site-loader': LocalJSX.IlSiteLoader & JSXBase.HTMLAttributes<HTMLIlSiteLoaderElement>;
    }
  }
}


