/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@inspirationlabs/router';

export namespace Components {
  interface SiteLoader {
    /**
    * The base domain for the project
    */
    'baseDomain': string;
    /**
    * Check for a router match
    */
    'match': MatchResults;
  }
}

declare global {


  interface HTMLSiteLoaderElement extends Components.SiteLoader, HTMLStencilElement {}
  var HTMLSiteLoaderElement: {
    prototype: HTMLSiteLoaderElement;
    new (): HTMLSiteLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'site-loader': HTMLSiteLoaderElement;
  }
}

declare namespace LocalJSX {
  interface SiteLoader {
    /**
    * The base domain for the project
    */
    'baseDomain'?: string;
    /**
    * Check for a router match
    */
    'match'?: MatchResults;
  }

  interface IntrinsicElements {
    'site-loader': SiteLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'site-loader': LocalJSX.SiteLoader & JSXBase.HTMLAttributes<HTMLSiteLoaderElement>;
    }
  }
}


